# Build Stage
FROM node:16-alpine AS build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY . .

# Build the project
RUN npm run build

# Production Stage
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy only the built files and package files from the build stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

COPY --from=build /app/.env.example ./.env.example

# Install only production dependencies
RUN npm install --production

# Expose the port the app runs on
EXPOSE 9090

# Start the application with node
CMD ["node", "dist/main"]